# This is a basic workflow to help you get started with Actions

name: CI with maven

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install
      
    - name: Experiment
      run:  |
        pwd
      
    - name: Build with Maven
      run: mvn -B test

    - name: Generate JaCoCo Badge
      uses: cicirello/jacoco-badge-generator@v2
      with:
        generate-branches-badge: true
        
    - name: Pushes test file
      uses: thisisDharam/jacoco-multi-module-sample@v2
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'module3/target/site/jacoco-aggregate/jacoco.csv'
        destination_repo: 'jacoco-multi-module-sample/module3/'
        destination_folder: 'target'
        user_email: 'singhdharam.be@gmail.com'
        user_name: 'thisisDharam'
        commit_message: 'A custom message for the commit'
